### ISSUE TITLE
Filtering for a label that is a subset of another will show both results

### ISSUE THREAD

**Issue by erinspace** [faustomorales/qsl#14]
Hi again! Also repeating, thanks for this awesome tool and it's so easy to use! This one was very easily gotten around by just changing our label names, but we didn't notice til a bit into the activity. 

## Description

If your labels contain a subset of one another filtering for the word contained in both will show results for both labels

## Reproduction

- Have labels that contain each other
    - ex: "Cat" and "Not Cat"
- Filter for just "Cat"
- Notice that both "Cat" and "Not Cat" labels show up

![qsl_label_in](https://user-images.githubusercontent.com/801594/214063840-c0e2e2ee-c8f9-4e2f-96f8-00f12f05feef.gif)

**Comment by faustomorales** [comment]
Ah, so my suggestion here is based on knowing that this is a really simple filtering algorithm. It's literally `str(query) in str(label_string)`. So if you had filtered for "Type: Cat" instead of "Cat" you would have achieved the desired result. We can make this filtering more sophisticated, but I don't think this issue requires it, so I'm closing it, given the simple workaround. Please report back if you disagree!
